### PR TITLE
Feature/whitelist images by token

### LINKED ISSUE #200: Whitelist images by tokenid
Show user a trust warning in the image frame and let them click something to load the image if they are okay with trusting the source.

### PR DESCRIPTION
**Pull request by rannyeribaptist**
Hi everyone, back in here for another improvement! 🚀

I've been working on issue #200 for a while now, and it's finally here. I have added the disclaimer text along with 2 buttons for every token view. So you have the option to see it once, or to trust that token and never be prompted with the disclaimer for that specific token again.

I also thought it was a good idea to add a button to hide the token, so if you accidentally clicked to trust the token but you didn't want to, you can undo it.

All these behaviors can be seen in the video below:

https://user-images.githubusercontent.com/14826006/178577769-259586fc-1b3d-41d3-966e-00ab0f8d4921.mov

image
image
image

closes #200

### CODE REVIEW

**Comment by piggydoughnut** [comment]
I am happy with this.

One last thing - can we please rename "Disclaimer" to "Image Preview Disclaimer". It is just being called just Disclaimer is not really saying what it is. 🙏🏽  Thank you.

**Comment by rannyeribaptist** [comment]
Changes implemented as described by @piggydoughnut

**Comment by piggydoughnut** [comment]
Looks great 🆗  @rannyeribaptist  All go from me.

**Review by piggydoughnut — APPROVED** [review]
👍🏽

**Pull request merged**
