### PR TITLE
103 token wallet 

### LINKED ISSUE #103: Change the side menu to fit new design
## New Menu

- [ ] no token value and no used price estimates
- [ ] filter at the top - all, nfts, other
- [ ] header change - number of tokens plus tokel amount held by the current address
- [ ] NFT labels for tokens which have supply 1
- [ ] search - filter tokens in the list ( in the future we will add an option of also showing results for tokens on the chain)

sideMenu-new

## Old Menu
sideMenu-old

### LINKED ISSUE #104: Token detail widget for Fixed supply and NFTs
Figma https://www.figma.com/file/KHt6RPqitWphkuchA8vo0I/TOKEL-UI?node-id=3600%3A26396

The widget appears when clicking on any of the tokens in the wallet's token list.

- [ ] See more links will lead to the explorer showing the full `Description` or `Extra info` sections
- [ ] IPFS link will be an actual link we will create by uploading the file to IPFS on token creation, for now it can be a placeholder
- [ ] Trade on DEX button will open DEX in the future, for now it can be disabled
- [ ] token preview is image preview, audio preview, video preview. Preferably all of the listed but ofc depending on the difficulty of implementation. Image and audio must have.
- [ ] NFT preview differs from Fixed supply token preview

## NFT token detail

detailNFTwidget

## Fixed supply token detail

detailTokenwidget

### PR DESCRIPTION
**Pull request by piggydoughnut**
Closes #104 
Closes #103 

Plus extra sending widget.

### CODE REVIEW

**Comment by piggydoughnut** [comment]
Looks great!
There are a couple of things inconsistent with design though, which need tweaking.

## Transfer widget

- Holdings text small font just like on the wallet widget
- Amount text big white just like on the wallet widget
 
 ## Side menu listing
 
- no logos for token listing items.
-  Add number of tokens under the TOKEL value at the top.

##  Token detail 
- connect Copy widget to copy icon
- Add a link to link icon.
- Replace both icons with already existing icons which are used in  or TxInformation  
- All token detail information should not overflow, so we dont see the scrollbar. Add limited chars to each Tokel detail item and … If it overflows that limit, then  make ... clickable   -> it will lead to the token detail on explorer, so in case users want to see the whole text they can read it on explorer
- Make space for IPFS link   (it is in the design) 
- NFTs - Make a space for an image, dataAsJson will have an IPFS link, for now just simulate with a normal url with an image please.  It will need to accept all sorts of formats image, audio, video. Making it work just for image/gif right now is enough.

**Comment by NutellaLicka** [comment]
I like the Tokel logo beside the TKL wallet amounts! This could also benefit from the dollar amount shown in this design
https://i.gyazo.com/ce63e441b01b586b1552183c17d1e4a7.png

Tokens won't have a logo though, as Daria mentioned.

Are we going to output the creator as a pubkey or as a normal address? I'm leaning toward a public key as show here.

I like the 'This is an NFT. You own the only one!' aha. Nice touch.

Can you search by any other parameter than name?

**Comment by acnebs** [comment]
All sounds good.

@NutellaLicka currently TKL isn't listed on any exchange right? So doesn't have a fiat value. Do you want to calculate value in some indirect way?

Initially I had the search just by `name`, but I've now changed it to include `description` as well. Other than that not sure there is anything we can usefully search by, except the URL in the tokel standard data.

**Comment by piggydoughnut** [comment]
Copy icon on the Generate New Address somehow went transparent. 
Screen Shot 2021-09-09 at 12 52 58 PM

**Comment by piggydoughnut** [comment]
This needs a bit of fixing before we merge. 

Screen Shot 2021-10-01 at 5 41 11 PM

**Pull request merged**
